M48
; DRILL file {KiCad 7.0.9} date Thu Aug 22 03:32:59 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-22T03:32:59-10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X5.6709Y-3.2244
X5.6709Y-3.3228
X5.8677Y-3.0276
X6.0646Y-3.2244
X6.0646Y-3.3228
T0
M30
